secrets:
  twitch_client_id:
    file: ./secrets/twitch_client_id
  twitch_client_secret:
    file: ./secrets/twitch_client_secret
    
services:
  angular-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-website
    ports:
      - "8080:8080"

  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  angular-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]

  twitch-api:
    build: ./twitch-backend
    ports:
      - "3000:3000"
    secrets:
      - twitch_client_id
      - twitch_client_secret
    restart: unless-stopped