import { Item } from './about-item.model';


export const Items: Item[] = [
    {
        id: 'mm-coffee',
        firstTitle: 'Look!',
        lastTitle: 'That\'s Me!',
        subTitle: 'Husband, dad, designer, diyer, gamer from the midwest',
        about: '',
        link1: 'https://www.linkedin.com/in/calebmackey',
        link2: 'https://github.com/midwest-mackey',
        link3: 'https://m.twitch.tv/midwestmackey/home',
        link4: 'https://discord.gg/zp8FNHUewS',
        link5: 'https://www.instagram.com/midwest.mackey/',
        link6: 'https://www.tiktok.com/@midwest.mackey?_t=ZT-8u7Bm4i0kuc&_r=1',
        link7: '',
        link8: '',
        link9: '',
        link10: '',
        link11: '',
        link12: '',
        link13: '',
        link14: '',
        css: 'flex-column offset align-items-center inset',
    },
    {
        id: 'mm-heart-life-full',
        firstTitle: 'Husband',
        lastTitle: 'Life',
        subTitle: 'Happily married for 10 years',
        about: 'Living life each day and supported by the best wife a guy could ask for! We spend much of our time together gaming, traveling, hitting up concerts (most likely MGK), and overall just enjoying our life spent together. ',
        link1: '',
        link2: '',
        link3: '',
        link4: '',
        link5: 'https://www.instagram.com/midwest.mackey/',
        link6: '',
        link7: '',
        link8: '',
        link9: '',
        link10: '',
        link11: '',
        link12: '',
        link13: '',
        link14: '',
        css: 'flex-column offset align-items-end',
    },
    {
        id: 'mm-dabb',
        firstTitle: 'Dad',
        lastTitle: 'Life',
        subTitle: '2 Kids, 3 cats 🐈‍⬛ a dozen chickens 🐔 and possibly a squirrel... 🐿️',
        about: 'Proud dad of 2, trying to squeeze as much time out of life. Attempting to raise 2 well behaved kids and teaching them how to be civilized. We strive to spend as much time as a family, eating dinner together, having movie nights, and showing them the world. Not sure how I am doing, but I am trying my best to show up for them each day.\nNOTE: Pretty sure the chickens are doing better at being civilized so far!',
        link1: '',
        link2: '',
        link3: '',
        link4: '',
        link5: 'https://www.instagram.com/midwest.mackey/',
        link6: '',
        link7: '',
        link8: '',
        link9: '',
        link10: '',
        link11: '',
        link12: '',
        link13: '',
        link14: '',
        css: 'col-auto ms-auto align-items-start mirror',
    },
    {
        id: 'mm-reading',
        firstTitle: 'Education',
        lastTitle: '',
        subTitle: 'Bachelors of Fine Arts, Graphic Design, Iowa State University',
        about: 'Attended ISU from 2008 - 2013 to attain a degree in design to pursue a career. I spent much of my time focusing on digital media, additional focus in computer science, engineering studies, and Human Computer Interaction. I had a desire to utilize my degree toward digital web interfaces, and never knew where it would actually lead me. ',
        link1: 'https://www.linkedin.com/in/calebmackey',
        link2: '',
        link3: '',
        link4: '',
        link5: '',
        link6: '',
        link7: '',
        link8: '',
        link9: '',
        link10: '',
        link11: 'https://www.design.iastate.edu/academics/undergraduate-programs/bachelor-of-fine-arts-in-graphic-design/',
        link12: '',
        link13: '',
        link14: '',
        css: 'flex-column offset align-items-end',
    },
    {
        id: 'mm-work',
        firstTitle: 'My',
        lastTitle: 'Nine-to-five',
        subTitle: 'Professional UX consultant with 10 years experience',
        about: 'My professional career has taken me somewhere I never dreamed of. I have spent much of my days designing and problem solving enterprise level systems for fortune 500 companies. I spent the first 8+ years of my professional life designing for an insurance company through Berkley Technology Services, which let me learn and hone my design skills solving tough problems for enterprise level systems. Now I am enjoying my time working for Lean Techniques, which allows me to consult for various clients and broaden my skills. Currenlty I am consulting for Vermeer Corporation on their enterprise level systems. You can also find me from time to time designing for Mumo Systems and their integrations with Atlassian software. ',
        link1: 'https://www.linkedin.com/in/calebmackey',
        link2: '',
        link3: '',
        link4: '',
        link5: '',
        link6: '',
        link7: 'https://leantechniques.com/',
        link8: 'https://www.berkley.com/',
        link9: 'https://www.vermeer.com/na',
        link10: 'https://www.mumosystems.com/',
        link11: '',
        link12: '',
        link13: '',
        link14: '',
        css: 'mt-5 mirror flex-column offset backset align-items-end',
    },
    {
        id: 'mm-dabb',
        firstTitle: 'Personal',
        lastTitle: 'Time',
        subTitle: 'Woodworking, home-flipping, electrical, cars, home-lab, gaming, tinkering',
        about: 'In the small amount of free time, I stay busy with my plethura of ADHD hobbies and interests. You can find me honing my woodworking skills in the shop, remodeling our house to make it better from floor to ceiling, modding my car, or learning something new with electrical work, my home lab and network, or tinkering on something I have never touched or have no idea how to do.\nCheckout some of projects and progress.',
        link1: '',
        link2: 'https://github.com/midwest-mackey',
        link3: '',
        link4: '',
        link5: 'https://www.instagram.com/midwest.cr3?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
        link6: '',
        link7: '',
        link8: '',
        link9: '',
        link10: '',
        link11: '',
        link12: 'https://stack.midwestmackey.com/',
        link13: '',
        link14: '/projects',
        css: 'mt-5 col-auto ms-auto align-items-start mirror',
    },
    {
        id: 'mm-skull',
        firstTitle: '',
        lastTitle: 'About this site',
        subTitle: 'Just a guy trying to learn new things',
        about: 'Trying to be a better version of myself each and every day.\nThis site is my space of learning, testing, and failing to understand code. Everything you see is self taught, self built, and self hosted.\nThank you visiting and supporting me\nCheckout my github to judge my code (its gonna be bad).\nMaybe buy me a coffee to support my work?',
        link1: '',
        link2: 'https://github.com/midwest-mackey',
        link3: '',
        link4: '',
        link5: '',
        link6: '',
        link7: '',
        link8: '',
        link9: '',
        link10: '',
        link11: '',
        link12: '',
        link13: 'https://www.buymeacoffee.com/midwestmackey',
        link14: '',
        css: 'nmt-5 col-auto ms-auto mirror align-items-end flex-row-reverse',
    },
    // {
    //     id: 'coming-soon',
    //     firstTitle: 'More',
    //     lastTitle: 'to come!',
    //     subTitle: 'I don’t know what I am doing yet. It’s only a matter of time until I figure it out.',
    //     about: 'Help me out by supporting my work, give me a follow, or buy me a coffee!',
    //     link1: '',
    //     link2: 'https://github.com/midwest-mackey',
    //     link3: '',
    //     link4: '',
    //     link5: '',
    //     link6: '',
    //     link7: '',
    //     link8: '',
    //     link9: '',
    //     link10: '',
    //     link11: '',
    //     link12: '',
    //     link13: '',
    //     link14: '',
    //     css: 'col-auto ms-auto align-items-end flex-row-reverse',
    // },
];
