import { Item } from './about-item.model';

// css-options: 'flex-column offset mirror backset',

export const Items: Item[] = [
    {
        id: 'mm-coffee',
        firstName: 'Hey',
        lastName: 'That\'s Me!',
        position: 'Husband, dad, designer, diyer, gamer from the midwest',
        about: 'Hi there, I\'m Caleb! I thrive on creating meaningful and intuitive experiences for users through my expertise that I have gathered over the last 10 years in the field. I have successfully helped numerous companies improve their digital presence and tools.',
        email: '',
        phone: '',
        cell: '',
        teamsURL: '',
        linkedIn: '',
        link: '',
        css: 'flex-column offset align-items-center inset',
    },
    {
        id: 'mm-heart-life-full',
        firstName: 'Husband',
        lastName: '',
        position: 'loading',
        about: 'This is an ever growing project, I am learning as I go to create and add content!',
        email: '',
        phone: '',
        cell: '',
        teamsURL: '',
        linkedIn: '',
        link: '',
        css: ' flex-column offset align-items-end',
    },
    {
        id: 'mm-dabb',
        firstName: 'Dad of 2',
        lastName: 'kiddos',
        position: '...oh, also 3 cats & a dozen chickens',
        about: 'Proud dad of 2, trying to squeeze as much time out of life. Attempting to raise 2 well behaved kids and teaching them how to be civilized. Pretty sure the chickens are doing better then them, thus far!',
        email: '',
        phone: '',
        cell: '',
        teamsURL: '',
        linkedIn: '',
        link: '',
        css: 'mt-5 col-auto ms-auto align-items-start mirror',
    },
    {
        id: 'coming-soon',
        firstName: 'Check',
        lastName: 'Back Later!',
        position: 'Work in progress',
        about: 'This is an ever growing project, I am learning as I go to create and add content! Thanks for checking it out and supporting me!',
        email: '',
        phone: '',
        cell: '',
        teamsURL: '',
        linkedIn: '',
        link: '',
        css: 'mt-5 col-auto ms-auto align-items-center',
    },
];
