
import { Project } from './project.model';

export const Projects: Project[] = [
    { id: '1', name: 'coming-soon', alts: ''   },
    { id: '3', name: 'mm-battery-empty', alts: ''  },
    { id: '4', name: 'left-shark', alts: ''  },
    { id: '5', name: 'midwest-mackey', alts: ''  },
    { id: '6', name: 'mm-blow-kiss', alts: ''  },
    { id: '7', name: 'mm-books', alts: ''  },
    { id: '8', name: 'mm-cat-hi', alts: ''  },
    { id: '9', name: 'mm-coffee', alts: ''  },
    { id: '10', name: 'mm-confetti', alts: ''  },
    { id: '11', name: 'mm-dabb', alts: ''  },
    { id: '12', name: 'mm-dad-joke', alts: ''  },
    { id: '13', name: 'mm-empty', alts: ''  },
    { id: '14', name: 'mm-headshot', alts: ''  },
    { id: '15', name: 'mm-heart-balloons', alts: ''  },
    { id: '16', name: 'mm-heart-emoji-balloons', alts: ''  },
    { id: '17', name: 'mm-heart-life-empty', alts: ''  },
    { id: '18', name: 'mm-heart-life-full', alts: ''  },
    { id: '19', name: 'mm-heart-sticker', alts: ''  },
    { id: '20', name: 'mm-heart-thinking', alts: ''  },
    { id: '21', name: 'mm-heart-throwing', alts: ''  },
    { id: '22', name: 'mm-jump-hooray', alts: ''  },
    { id: '23', name: 'mm-lost', alts: ''  },
    { id: '24', name: 'mm-love-you-heaps', alts: ''  },
    { id: '25', name: 'mm-mad', alts: ''  },
    { id: '26', name: 'mm-magic8ball', alts: ''  },
    { id: '27', name: 'mm-me', alts: ''  },
    { id: '28', name: 'mm-nope', alts: ''  },
    { id: '29', name: 'mm-oh-hi-there', alts: ''  },
    { id: '30', name: 'mm-pillow', alts: ''  },
    { id: '31', name: 'mm-question', alts: ''  },
    { id: '32', name: 'mm-reading', alts: ''  },
    { id: '33', name: 'mm-shark', alts: ''  },
    { id: '34', name: 'mm-sitting', alts: ''  },
    { id: '35', name: 'mm-skull', alts: ''  },
    { id: '36', name: 'mm-standing-proud', alts: ''  },
    { id: '37', name: 'mm-wave', alts: ''  },
    { id: '38', name: 'mm-work', alts: ''  },
];
