
import { Logo } from './logo.model';

export const Logos: Logo[] = [
    { id: 'ADM', name: 'Admiral Insurance Company                                    ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#15254C', alpha: ''      },
    { id: 'AIC', name: 'Acadia Insurance Company                                     ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#0E553F', alpha: ''      },
    { id: 'ART', name: 'Berkley International Aseguradora De Riesgos Del Trabajo S.A.', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BAC', name: 'Berkley International Service LLC                            ', primary: 'BIL', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BAH', name: 'Berkley Accident and Health                                  ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BAM', name: 'Berkley Alliance Managers                                    ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#004987', alpha: ''      },
    { id: 'BAP', name: 'Berkley Asset Protection Underwriting Managers, LLC          ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#0079A8', alpha: ''      },
    { id: 'BAR', name: 'Berkley Agribusiness Risk Specialists                        ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#4bA485', alpha: ''      },
    { id: 'BAS', name: 'Berkley Argentina Seguros                                    ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: '-alpha'},
    { id: 'BCA', name: 'Berkley Insurance Asia                                       ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#000000', alpha: ''      },
    { id: 'BCI', name: 'Berkley Custom Insurance                                     ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BCP', name: 'Berkley Construction Professionals                           ', primary: '●'  , alts: ''   , ico: 'BAM', fav: 'BAM', theme: ''       , alpha: ''      },
    { id: 'BCR', name: 'Berkley Cyber Risk Solutions                                 ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#7CC14D', alpha: ''      },
    { id: 'BCS', name: 'Berkley Construction Solutions                               ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#FF6C00', alpha: ''      },
    { id: 'BDH', name: 'Berkley Insurance Asia Hong Kong                             ', primary: 'BCA', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BDJ', name: 'Berkley Insurance Asia Japan                                 ', primary: 'BCA', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BDL', name: 'Berkley Insurance Asia Labuan                                ', primary: 'BCA', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BDP', name: 'Berkley Design Professional Underwriters                     ', primary: '●'  , alts: ''   , ico: 'BAM', fav: 'BAM', theme: ''       , alpha: ''      },
    { id: 'BDS', name: 'Berkley Insurance Asia Singapore                             ', primary: 'BCA', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BEC', name: 'Berkley Equine & Cattle                                      ', primary: '●'  , alts: '●●' , ico: '●'  , fav: '●'  , theme: '#095540', alpha: '-alpha'},
    { id: 'BEI', name: 'Berkley Entertainment                                        ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#D49902', alpha: ''      },
    { id: 'BER', name: 'Berkley Enterprise Risk Solutions                            ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BES', name: 'W.R. Berkley European Services GmbH                          ', primary: 'EAG', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BEU', name: 'Berkley European Underwriters AS                             ', primary: 'BOS', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BFM', name: 'Berkley Fire & Marine Underwriters                           ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#0093C9', alpha: ''      },
    { id: 'BFS', name: 'Berkley Financial Specialists                                ', primary: '●'  , alts: '●●' , ico: '●'  , fav: '●'  , theme: '#414042', alpha: ''      },
    { id: 'BGU', name: 'Berkley Global Underwriters LLC                              ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BHC', name: 'Berkley Healthcare                                           ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#76777A', alpha: ''      },
    { id: 'BHF', name: 'Berkley Healthcare Financial Lines                           ', primary: '●'  , alts: ''   , ico: 'BHC', fav: 'BHC', theme: ''       , alpha: ''      },
    { id: 'BHP', name: 'Berkley Healthcare Professional Underwriters                 ', primary: '●'  , alts: ''   , ico: 'BHC', fav: 'BHC', theme: ''       , alpha: ''      },
    { id: 'BID', name: 'Berkley International Seguros Mexico SA de CV                ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BIF', name: 'Berkley International Fianzas Mexico SA                      ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BIL', name: 'Berkley International Latinoamerica SA                       ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BIN', name: 'Berkley Industrial Comp                                      ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#003B45', alpha: ''      },
    { id: 'BIS', name: 'Berkley International Seguros S.A.                           ', primary: 'BAS', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: '-alpha'      },
    { id: 'BIX', name: 'Berkley International Mexico                                 ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BKI', name: 'Berkley Re Asia (Hong Kong)                                  ', primary: 'PAC', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BLA', name: 'Berkley Latin America and Caribbean Managers                 ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BLG', name: 'Berkley Luxury Group                                         ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#095540', alpha: ''      },
    { id: 'BLS', name: 'Berkley Life Sciences                                        ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#005CB9', alpha: ''      },
    { id: 'BMG', name: 'Berkley Mid Atlantic Group                                   ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BMI', name: 'Berkley Managers Insurance Services, LLC                     ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#005B82', alpha: ''      },
    { id: 'BMM', name: 'Berkley Medical Management Services                          ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#F16A2C', alpha: ''      },
    { id: 'BMP', name: 'Berkley Management Protection                                ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#100C50', alpha: ''      },
    { id: 'BMT', name: 'Berkley Tech Labs, A.M. Alternative Markets Technology Group ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BMU', name: 'Berkley Healthcare Medical Professional                      ', primary: 'BHP', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BNP', name: 'Berkley North Pacific Group                                  ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#03563E', alpha: ''      },
    { id: 'BNU', name: 'Berkley Net Underwriters                                     ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#77BC1F', alpha: ''      },
    { id: 'BOG', name: 'Berkley Oil and Gas                                          ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#F08E20', alpha: ''      },
    { id: 'BOS', name: 'Berkley Offshore Underwriting Managers (US)                  ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#929497', alpha: ''      },
    { id: 'BOU', name: 'Berkley Offshore Underwriting Managers, UK Limited           ', primary: 'BOS', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BPE', name: 'Berkley Public Entity Managers, LLC                          ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#195991', alpha: ''      },
    { id: 'BPL', name: 'Berkley Professional Liability                               ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#897449', alpha: ''      },
    { id: 'BPP', name: 'Berkley Product Protection                                    ',primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BPR', name: 'Berkley Global Product Recall Management                     ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BPS', name: 'Berkley Program Specialists                                  ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BPT', name: 'Berkley Prime Transportation                                 ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#009345', alpha: ''      },
    { id: 'BRC', name: 'Berkley Risk Administrators Company                          ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#15284B', alpha: ''      },
    { id: 'BRE', name: 'Berkley Renewable Energy                                     ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#65BC54', alpha: ''      },
    { id: 'BRS', name: 'Berkley Re Solutions                                         ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BSB', name: 'Berkley Small Business Solutions                             ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#4C9C2E', alpha: ''      },
    { id: 'BSE', name: 'Berkley Southeast Insurance Group                            ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BSG', name: 'Berkley Surety Group                                         ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BSL', name: 'Berkley Select                                               ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#0095dA', alpha: ''      },
    { id: 'BSP', name: 'Berkley Service Professional Underwriters                    ', primary: '●'  , alts: ''   , ico: 'BAM', fav: 'BAM', theme: ''       , alpha: ''      },
    { id: 'BSS', name: 'Berkley Shared Services                                      ', primary: 'WRB', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BTK', name: 'Berkley Technology Services UK LLC                           ', primary: 'BTS', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BTL', name: 'Berkley Transactional                                        ', primary: '●'  , alts: ''   , ico: 'BPL', fav: 'BPL', theme: ''       , alpha: '-alpha'},
    { id: 'BTS', name: 'Berkley Technology Services                                  ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BTU', name: 'Berkley Technology Underwriters                              ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#0E553F', alpha: ''      },
    { id: 'BUC', name: 'Berkley Canada                                               ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'BUK', name: 'Berkley Re UK Limited                                        ', primary: 'PAC', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'BXM', name: 'BXM Insurance Services, Inc.                                 ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#BF9B5F', alpha: ''      },
    { id: 'CCI', name: 'Carolina Casualty Insurance Group                            ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#7BAED3', alpha: ''      },
    { id: 'CLA', name: 'Berkley Classics                                             ', primary: '●'  , alts: '●●' , ico: '●'  , fav: '●'  , theme: '#0F553F', alpha: ''      },
    { id: 'CRI', name: 'Berkley Crime                                                ', primary: '●'  , alts: '●'  , ico: 'BFS', fav: 'BFS', theme: ''       , alpha: ''      },
    { id: 'CWG', name: 'Continental Western Group                                    ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'DNA', name: 'DNA                                                          ', primary: ''   , alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'DUK', name: 'WRBC Development UK Limited                                  ', primary: 'WRB', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'EAG', name: 'W. R. Berkley Europe AG                                      ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#8FD5BD', alpha: ''      },
    { id: 'ENV', name: 'Berkley Environmental                                        ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#00567C', alpha: ''      },
    { id: 'ESP', name: 'W. R. Berkley Europe AG, Spain Branch                        ', primary: '●'  , alts: ''   , ico: 'EAG', fav: 'EAG', theme: ''       , alpha: ''      },
    { id: 'EST', name: 'E&S Tech                                                     ', primary: ''   , alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'FSS', name: 'Berkley Financial & Statutory Services BFINS                 ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'GER', name: 'W. R. Berkley Europe AG, Germany Branch                      ', primary: '●'  , alts: ''   , ico: 'EAG', fav: 'EAG', theme: ''       , alpha: ''      },
    { id: 'GTU', name: 'Gemini Transportation Underwriters                           ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#E95225', alpha: ''      },
    { id: 'IAR', name: 'Berkley Argentina De Reaseguros S.A.                         ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'IBR', name: 'Berkley International Do Brasil Seguros S.A.                 ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'ICA', name: 'Interlaken Capital Aviation Services                         ', primary: '●'  , alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'ICO', name: 'Berkley International Seguros Colombia S.A.                  ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'IDI', name: 'Intrepid Direct                                              ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#F68720', alpha: ''      },
    { id: 'IPR', name: 'Berkley International Puerto Rico                            ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'KRM', name: 'Key Risk Management Services                                 ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#153A6F', alpha: ''      },
    { id: 'LON', name: 'WRB Underwriting                                             ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#231F20', alpha: ''      },
    { id: 'MAN', name: '52 Lime Street Management Limited                            ', primary: '●'  , alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'MEC', name: 'Midwest Employers Casualty Company                           ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#003056', alpha: ''      },
    { id: 'MLM', name: 'Monitor Liability Managers                                   ', primary: 'BSL', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'MPL', name: 'Milton Arbitrage Partners, LLC                               ', primary: 'WRB', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'NIC', name: 'Nautilus Insurance Company                                   ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#003B4C', alpha: ''      },
    { id: 'NOR', name: 'W. R. Berkley Europe AG, Norway Branch                       ', primary: '●'  , alts: ''   , ico: 'EAG', fav: 'EAG', theme: ''       , alpha: ''      },
    { id: 'ODR', name: 'Berkley Insurance Company (representative Colombia)          ', primary: 'BLA', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'ONE', name: 'Berkley One                                                  ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#00BCb4', alpha: ''      },
    { id: 'PAC', name: 'Berkley Re Asia Pacific                                      ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'PEG', name: 'Preferred Employers Insurance Company                        ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#015440', alpha: ''      },
    { id: 'POR', name: 'Berkley Portugal                                             ', primary: '●'  , alts: ''   , ico: 'EAG', fav: 'EAG', theme: ''       , alpha: '-alpha'},
    { id: 'RAM', name: 'Berkley Re America, LLC                                      ', primary: 'PAC', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'RAU', name: 'Berkley Re Australia                                         ', primary: 'PAC', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'RCM', name: 'Berkley Recreational Marine                                  ', primary: '●'  , alts: '●●' , ico: '●'  , fav: '●'  , theme: '#0F553F', alpha: ''      },
    { id: 'RIC', name: 'Berkley Human Services                                       ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'RSI', name: 'Berkley Aspire                                               ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#0089BB', alpha: ''      },
    { id: 'RSP', name: 'Berkley Re Asia (Singapore)                                  ', primary: 'PAC', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'RSS', name: 'Berkley Regional Shared Services                             ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'SAU', name: 'Berkley International Seguros S.A. (Uruguay)                 ', primary: '●'  , alts: '●'  , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'SIT', name: 'Specialty IT Services                                        ', primary: 'WRB', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'SLU', name: 'W. R. Berkley Europe AG, Spain SLU                           ', primary: 'ESP', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'SMI', name: 'Select Marketing Insurance (Preferred Connect)               ', primary: 'PEG', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'SVC', name: 'WRBC Services, Ltd.                                          ', primary: 'WRB', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'SWE', name: 'W. R. Berkley Europe AG, Sweden Branch                       ', primary: 'EAG', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'USG', name: 'Union Standard Insurance Group                               ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'VEL', name: 'Vela Insurance Services                                      ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#007298', alpha: ''      },
    { id: 'VUM', name: 'Verus Underwriting Managers                                  ', primary: '●'  , alts: '●'  , ico: '●'  , fav: '●'  , theme: '#C30017', alpha: ''      },
    { id: 'WAU', name: 'Berkley Insurance Australia                                  ', primary: '●'  , alts: ''   , ico: 'WRB', fav: 'WRB', theme: ''       , alpha: ''      },
    { id: 'WRB', name: 'W. R. Berkley Corporation                                    ', primary: '●'  , alts: '●●●', ico: '●'  , fav: '●'  , theme: '#095540', alpha: ''      },
    { id: 'WSS', name: 'WRBC Support Services                                        ', primary: 'WRB', alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: ''      },
    { id: 'ABC', name: 'a berkley company (endorsement)                              ', primary: '●'  , alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: '-alpha'},
    { id: 'AIS', name: 'an internal services group (endorsement)                     ', primary: '●'  , alts: ''   , ico: ''   , fav: ''   , theme: ''       , alpha: '-alpha'},
    { id: 'AMR', name: 'NON BERKLEY - Arizona Municipal Risk Retention Pool          ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#EE7421', alpha: ''      },
    { id: 'STS', name: 'NON BERKLEY - States                                         ', primary: '●'  , alts: ''   , ico: '●'  , fav: '●'  , theme: '#D11242', alpha: ''      },
];
